### PR TITLE
add `new` mode

### PR DESCRIPTION
**Pull request by thacuber2a03**
this PR adds the `new` shortcut mode to UmBox, so that users can create a new directory and initialize a box inside of it with one command: `umbox new <box_name> [<preset>]`

I'm also considering the possibility of allowing preinstallation of dependencies: `umbox new <box_name> [<preset>] [<dependency_list>]`

it should only be merged once [os.um](https://git.sr.ht/~mrms/osum) recieves a `chdir(path)` function, and I believe I sent a patchset to do so already

also indentation isn't consistent in the repo, might want to check that too :/

### CODE REVIEW

**Comment by thacuber2a03** [comment]
> I'm also considering the possibility of allowing preinstallation of dependencies: `umbox new <box_name> [<preset>] [<dependency_list>]`

I have realized that this form is ambiguous. it would only work if the second argument was always taken to be the init preset and the rest the dependencies, or if the init preset was at the *end* of the list

so either:
`umbox new <box_name> [<preset> [<dependency_list>]]`
or
`umbox new <box_name> [<dependency_list>] [<preset>]`

**Comment by thacuber2a03** [comment]
I find out the first one is the most useful, as I think people usually would, with a console application, init with Umka, and with a graphical application, init with Tophat or other frameworks, so the lines would look like `umbox new <consoleBox> umka` or `umbox new <graphicalBox> tophat`

**Comment by marekmaskarinec** [comment]
I don't see a reason to have two similar, but different commands. It just creates needless confusion. I suggest the functionality of the `new` command is merged into `init`. You don't need to worry about breaking changes.

**Comment by skejeton** [comment]
> > I'm also considering the possibility of allowing preinstallation of dependencies: `umbox new <box_name> [<preset>] [<dependency_list>]`
> 
> I have realized that this form is ambiguous. it would only work if the second argument was always taken to be the init preset and the rest the dependencies, or if the init preset was at the _end_ of the list
> 
> so either: `umbox new <box_name> [<preset> [<dependency_list>]]` or `umbox new <box_name> [<dependency_list>] [<preset>]`

I think preset should be specified separately with `-p`, or something like this.

**Comment by marekmaskarinec** [comment]
Closing this, since `init` no longer has the limitations this was trying to mitigate.

**Pull request closed without merging**
